/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.2.0/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    alias(libs.plugins.graalvm.native)
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
    maven { url = uri("https://jitpack.io") }
}

dependencies {
    // This dependency is used by the application.
    implementation(libs.guava)
    implementation(libs.newpipe.extractor)
    implementation(libs.okhttp3)
    implementation(libs.nanojson)
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

application {
    // Define the main class for the application.
    mainClass = "dev.krtirtho.libnewpipe.NewPipe"
}

tasks.withType<AbstractArchiveTask>().configureEach {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

tasks.named("distTar").configure { enabled = false }
tasks.named("distZip").configure { enabled = false }


graalvmNative {
    binaries {
        named("main") {
            javaLauncher.set(javaToolchains.launcherFor {
                languageVersion.set(JavaLanguageVersion.of(17))
                vendor.set(JvmVendorSpec.matching("Oracle Corporation"))
            })
            debug.set(false)
            imageName.set("NewPipeCLI")
            mainClass.set(application.mainClass)
            sharedLibrary.set(false)

            buildArgs.addAll(listOf(
                "-Ob",
                "-H:+ReportExceptionStackTraces",
                "-H:+AllowIncompleteClasspath",
                "-H:EnableURLProtocols=http,https",
                "--no-fallback",
                "--gc=epsilon",
                "-H:CCompilerOption=-fpic",
                "-H:NativeLinkerOption=-fpic",
                "--initialize-at-run-time=dev.krtirtho.libnewpipe.NewPipe,org.schabi.newpipe.extractor.NewPipe,org.schabi.newpipe.extractor.services.youtube.YoutubeService"
            ))
        }
    }
}

tasks.register<Exec>("compressNativeImage") {
    group = "build"
    description = "Compress GraalVM native image binary with UPX"
    dependsOn("nativeCompile")
    commandLine("upx", "-9", "$buildDir/native/nativeCompile/NewPipeCLI")
}

tasks.named("nativeCompile") {
    finalizedBy("compressNativeImage")
}