import org.gradle.internal.os.OperatingSystem

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.2.0/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    alias(libs.plugins.graalvm.native)
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
    maven { url = uri("https://jitpack.io") }
}

dependencies {
    // This dependency is used by the application.
    implementation(libs.guava)
    implementation(libs.newpipe.extractor)
    implementation(libs.okhttp3)
    implementation(libs.nanojson)
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

application {
    // Define the main class for the application.
    mainClass = "dev.krtirtho.libnewpipe.NewPipe"
}

tasks.withType<AbstractArchiveTask>().configureEach {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

tasks.named("distTar").configure { enabled = false }
tasks.named("distZip").configure { enabled = false }


graalvmNative {
    binaries {
        named("main") {
            javaLauncher.set(javaToolchains.launcherFor {
                languageVersion.set(JavaLanguageVersion.of(25))
            })
            debug.set(false)
            imageName.set("NewPipeCLI")
            mainClass.set(application.mainClass)
            sharedLibrary.set(false)

            buildArgs.addAll(listOf(
                "-Ob",
                "-H:+ReportExceptionStackTraces",
                "-H:-CheckToolchain",
                "-H:+AllowIncompleteClasspath",
                "-H:EnableURLProtocols=http,https",
                "--no-fallback",
                "--gc=epsilon",
                "-H:CCompilerOption=-fpic",
                "-H:NativeLinkerOption=-fpic",
                "--initialize-at-run-time=dev.krtirtho.libnewpipe.NewPipe,org.schabi.newpipe.extractor.NewPipe,org.schabi.newpipe.extractor.services.youtube.YoutubeService"
            ))
        }
    }
}

val os = OperatingSystem.current()
val nativeBinaryName = if (os.isWindows) "NewPipeCLI.exe" else "NewPipeCLI"
val nativeBinaryPath = buildDir.resolve("native/nativeCompile/$nativeBinaryName")

tasks.register<Zip>("zipNativeImage") {
    group = "build"
    description = "Create a zip archive containing the native executable binary"
    dependsOn("nativeCompile")

    from(nativeBinaryPath.parentFile) {
        include(nativeBinaryName)
    }
    archiveFileName.set("NewPipeCLI.zip")
    destinationDirectory.set(layout.buildDirectory.dir("distributions"))
}

tasks.named("nativeCompile") {
    finalizedBy("zipNativeImage")
}
