/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.2.0/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    alias(libs.plugins.graalvm.native)
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
    maven { url = uri("https://jitpack.io") }
}

dependencies {
    // This dependency is used by the application.
    implementation(libs.guava)
    implementation(libs.newpipe.extractor)
    implementation(libs.okhttp3)

    // Logging dependency (required by NewPipeExtractor, simple implementation for CLI)
    implementation(libs.slf4j.simple)
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

application {
    // Define the main class for the application.
    mainClass = "org.example.App"
}

tasks.withType<AbstractArchiveTask>().configureEach {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

tasks.named("distTar").configure { enabled = false }
tasks.named("distZip").configure { enabled = false }


graalvmNative {
    binaries {
        named("main") {
            javaLauncher.set(javaToolchains.launcherFor {
                languageVersion.set(JavaLanguageVersion.of(17))
                vendor.set(JvmVendorSpec.matching("Oracle Corporation"))
            })
            debug.set(false)
            imageName.set("NewPipeCLI")
            mainClass.set(application.mainClass)
            sharedLibrary.set(false)

            buildArgs.add("--no-fallback")
//            buildArgs.add("--link-at-build-time")
//            buildArgs.add("--initialize-at-build-time")
            buildArgs.add("--no-server")
            buildArgs.add("--allow-incomplete-classpath")
            buildArgs.add("--gc=epsilon") // smaller runtime footprint
            buildArgs.add("--enable-url-protocols=http,https") // if only HTTP needed
        }
    }
}